from __future__ import annotations

import argparse
import json
from pathlib import Path

from churro.leaderboard import LeaderboardRow, summarize

HEADER = """# Churro leaderboard

One row per fingerprinted environment, generated by `tools/leaderboard.py` from
`data/fingerprints/*.json`. **Best model to train** is the `qwen3-v1` rung with
the highest signal rate (share of tasks where a GRPO group disagrees), counting
only rungs with at least {min_tasks} tasks. Details and caveats per env are in
`FINDINGS.md`.

| Environment | Answer-key check | Best model to train | Peak signal | Pass rate range | Rungs | Saturated | Binary reward |
|---|---|---|---|---|---|---|---|
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Write LEADERBOARD.md from the fingerprints")
    parser.add_argument("--fingerprints", type=Path, default=Path("data/fingerprints"))
    parser.add_argument("--out", type=Path, default=Path("LEADERBOARD.md"))
    parser.add_argument("--min-tasks", type=int, default=10)
    args = parser.parse_args()

    rows = [
        summarize(json.loads(path.read_text(encoding="utf-8")), min_tasks=args.min_tasks)
        for path in sorted(args.fingerprints.glob("*.json"))
    ]
    rows.sort(key=lambda r: -(r.best_signal or 0.0))
    table = "".join(_line(r) for r in rows)
    notes_path = args.fingerprints / "NOTES.md"
    notes = notes_path.read_text(encoding="utf-8") if notes_path.is_file() else ""
    args.out.write_text(HEADER.format(min_tasks=args.min_tasks) + table + notes, encoding="utf-8")
    print(f"wrote {args.out} ({len(rows)} environments)")


def _line(r: LeaderboardRow) -> str:
    signal = f"{r.best_signal:.0%} ± {r.best_signal_ci95:.0%}" if r.best_signal is not None else "-"
    passes = f"{r.pass_range[0]:.0%}–{r.pass_range[1]:.0%}" if r.pass_range else "-"
    return (
        f"| {r.env_id} | {r.grader_check or 'not run'} | {r.best_model or '-'} | {signal} | "
        f"{passes} | {r.rungs_measured}/5 | {'yes' if r.saturated else 'no'} | "
        f"{'yes' if r.binary_reward else 'no'} |\n"
    )


if __name__ == "__main__":
    main()
